### ISSUE TITLE
OpenEdx production setting error

### ISSUE THREAD

**Issue by vpadwalkar-cci** [regisb/openedx-install#14]
I have installed Ficus version of OpenEdx on Ubuntu 16.4 (AWS) and configured to work on localhost as --production settings. I am receiving "GET / HTTP/1.1" 400 26 ERROR. Please help

**Comment by regisb** [comment]
Hi @vpadwalkar-cci, thanks for reporting this issue! Have you followed the instructions given in this repo? At which step are you?

**Comment by nicaiseeric** [comment]
Hi @regisb , I did all the steps. supervisorctl status give all running and i can check opened port are fine. But I get "Uh oh, we are having some server issues.." when trying to access with a browser

**Comment by regisb** [comment]
@nicaiseeric please don't piggyback on an already existing issue with a different problem. @vpadwalkar-cci has a 400 error, while you have a 500 error. Please open a different issue where you describe your problem. You should include the error logs from supervisor, located in `/var/log/supervisor`.

I'll close this issue since I haven't received any feedback from @vpadwalkar-cci. Please don't hesitate to reopen it if you have not solved your problem.
